version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - ENDPOINT_SERVER=http://backend:8082
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - ENDPOINT_CLIENT=https://marianbay.click
      - ENDPOINT_SERVER=http://backend:8082

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./front-end/.next:/usr/share/nginx/html
      - ./front-end/public:/usr/share/nginx/html/public
    depends_on:
      - frontend
      - backend
    restart: always